### ISSUE TITLE
License of scrabble benchmarks

### ISSUE THREAD

**Issue by qwwdfsad** [akarnokd/akarnokd-misc#12]
Hi David,

We want to benchmark `kotlinx.coroutines.Flow` using reactive scrabble benchmark.
Recently, the original benchmarks were [republished](https://github.com/JosePaumard/jdk8-stream-rx-comparison-reloaded) under Apache 2.0, so we are able to publish them in our repository (that is also under Apache 2.0). But unfortunately, we cannot add comparison with Rx or Reactor (at least optimized versions, that are definitely derivative work from GPL code).

It would be very nice if you could re-publish reactive scrabble benchmarks under Apache 2.0 license or under any dual-license that is compatible with Apache 2.0, it is now possible when the original benchmarks are available under Apache 2.0 as well

**Comment by akarnokd** [comment]
Okay, how do I do that? Change the license header?

**Comment by qwwdfsad** [comment]
Yes, that's enough

**Comment by akarnokd** [comment]
Done.

**Comment by qwwdfsad** [comment]
Thanks!
