### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dwursteisen** [akarnokd/akarnokd-misc#6]
It's seems you're using a class that doesn't exist in the package or doesn't correctly imported in the [SingletonIteratorTest](https://github.com/akarnokd/akarnokd-misc/blob/master/src/test/java/hu/akarnokd/iterables/SingletonIteratorTest.java) java source file :

The [SingletonIterator](https://github.com/akarnokd/akarnokd-misc/blob/6fc1f45d09edf7e49969d19edbab0124de5f2fc7/src/test/java/hu/akarnokd/iterables/SingletonIteratorTest.java#L13) doesn't exist in java.util and is ot imported.

So the project can be build, if you don't comment this code.

**Comment by akarnokd** [comment]
Works for me. Verify you have Java 8 as the JDK and intellij is actually set to language level 8.

**Comment by dwursteisen** [comment]
```
gradlew build
```
give me this result : 
```
:compileTestJava
C:\ws\perso\akarnokd-misc-master\src\test\java\hu\akarnokd\iterables\SingletonIteratorTest.java:13: error: cannot find symbol
        Iterator<Integer> it = SingletonIterator.of(1);
                               ^
  symbol:   variable SingletonIterator
  location: class SingletonIteratorTest
1 error
:compileTestJava FAILED
```

I think that the problem is that the "missing" class is in the `jmh` source set, and that `the` test source set depends of the `main` source set instead of the `main` & the `jmh` source set

Adding `testCompile sourceSets.jmh.output` in the `dependencies` block fix the issue

**Comment by akarnokd** [comment]
Okay, the file is there: https://github.com/akarnokd/akarnokd-misc/blob/6fc1f45d09edf7e49969d19edbab0124de5f2fc7/src/jmh/java/hu/akarnokd/iterables/SingletonIterator.java

I don't use gradlew build on this project because the unit tests are ad-hoc and I tested some bugs occasioanlly with it.

```
gradlew jmh -Pjmh="*classname*"
```

this is how I run the benchmarks

**Comment by akarnokd** [comment]
Should be working now.
